services:
  landing:
    build:
      context: .
      dockerfile: Dockerfile.landing
    container_name: ${PROJECT_NAME}-landing
    restart: always
    ports:
      - ${PORT_LANDING}:80
    env_file:
      - .env
    volumes:
      - ./landing:/var/www/html
      - ./CHAT_HISTORY.md:/var/www/CHAT_HISTORY.md:ro
    networks:
      - joomla_network
    depends_on:
      - db

  joomla:
    image: joomla:5-php8.3-apache
    container_name: ${PROJECT_NAME}-joomla
    restart: always
    ports:
      - ${PORT_JOOMLA}:80
    env_file:
      - .env
    environment:
      - JOOMLA_DB_HOST=${JOOMLA_DB_HOST}
      - JOOMLA_DB_USER=${JOOMLA_DB_USER}
      - JOOMLA_DB_PASSWORD=${JOOMLA_DB_PASSWORD}
      - JOOMLA_DB_NAME=${JOOMLA_DB_NAME}
      - JOOMLA_ADMIN_USER=${JOOMLA_ADMIN_USERNAME}
      - JOOMLA_ADMIN_PASSWORD=${JOOMLA_ADMIN_PASSWORD}
      - JOOMLA_ADMIN_EMAIL=${JOOMLA_ADMIN_EMAIL}
      - JOOMLA_SITE_NAME=${JOOMLA_SITE_NAME}
    volumes:
      - ./joomla:/var/www/html
    networks:
      - joomla_network
    depends_on:
      - db

  db:
    image: "${MYSQL_IMAGE:-mysql:8.0}"
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    ports:
      - ${PORT_MYSQL}:3306
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${PROJECT_NAME}_db_data:/var/lib/mysql
    networks:
      - joomla_network

  phpmyadmin:
    image: "${PHPMYADMIN_IMAGE:-phpmyadmin:latest}"
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${PORT_PHPMYADMIN}:80"
    networks:
      - joomla_network

volumes:
  ${PROJECT_NAME}_db_data:


networks:
  joomla_network:
