services:
  joomla:
    image: joomla
    restart: always
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./joomla:/var/www/html
    networks:
      - joomla_network

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - joomla_network

volumes:
  db_data:


networks:
  joomla_network:
