FROM phpmyadmin/phpmyadmin:latest

# Konfiguration für größere Upload-Limits
RUN echo "upload_max_filesize = 128M" > /usr/local/etc/php/conf.d/uploads.ini \
    && echo "post_max_size = 128M" >> /usr/local/etc/php/conf.d/uploads.ini